'use client';
import { useEffect, useMemo, useState } from 'react';
import { AppShell, SectionTitle, StatusBadge, card, card2, muted } from '../../components/ops-ui';

type Doc={id:string;path:string;area:string;title:string;type:string;status:string;updated:string|null;tags:string[];excerpt:string;body:string};
type Projection={generatedAt:string;stats:{documents:number;areas:number};documents:Doc[]};
const AREA_LABELS:Record<string,string>={'00-Home':'Home','01-Projects':'Projects','02-Areas':'Areas','03-Resources':'Resources'};
function age(iso:string){const minutes=Math.max(0,Math.floor((Date.now()-Date.parse(iso))/60000));return minutes<1?'just now':minutes<60?`${minutes}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:`${Math.floor(minutes/1440)}d ago`;}
function displayLine(line:string){return line.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g,(_,target,label)=>label||target).replace(/`([^`]+)`/g,'$1').replace(/\*\*([^*]+)\*\*/g,'$1');}
function Markdown({body}:{body:string}){return <article className="space-y-2 text-sm leading-7 text-slate-300">{body.split('\n').map((line,index)=>{const text=displayLine(line.trim());if(!text)return <div key={index} className="h-1"/>;if(text.startsWith('### '))return <h3 key={index} className="pt-3 text-sm font-extrabold text-cyan-100">{text.slice(4)}</h3>;if(text.startsWith('## '))return <h2 key={index} className="pt-4 text-base font-extrabold text-slate-100">{text.slice(3)}</h2>;if(text.startsWith('# '))return <h1 key={index} className="text-xl font-black text-slate-50">{text.slice(2)}</h1>;if(/^[-*] /.test(text))return <div key={index} className="grid grid-cols-[10px_1fr] gap-2"><span className="text-cyan-400">•</span><span>{text.slice(2)}</span></div>;if(/^\d+\. /.test(text))return <div key={index} className="pl-3 text-slate-300">{text}</div>;if(text.startsWith('|'))return <div key={index} className="overflow-x-auto whitespace-pre font-mono text-[10px] text-slate-400">{text}</div>;return <p key={index}>{text}</p>;})}</article>}

export default function KnowledgePage(){
 const [data,setData]=useState<Projection|null>(null),[selected,setSelected]=useState<string>(''),[query,setQuery]=useState(''),[area,setArea]=useState('all'),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/knowledge',{cache:'no-store'}).then(async response=>{const value=await response.json();if(!response.ok||!value.ok)throw new Error(value.error||'Knowledge unavailable');setData(value);setSelected(value.documents.find((doc:Doc)=>doc.id==='00-Home/Home')?.id||value.documents[0]?.id||'');}).catch(caught=>setError(caught instanceof Error?caught.message:'Knowledge unavailable'));},[]);
 const docs=useMemo(()=>{const needle=query.trim().toLowerCase();return (data?.documents||[]).filter(doc=>(area==='all'||doc.area===area)&&(!needle||`${doc.title} ${doc.tags.join(' ')} ${doc.excerpt} ${doc.body}`.toLowerCase().includes(needle)));},[data,query,area]);
 const active=data?.documents.find(doc=>doc.id===selected)||docs[0]||null;const fresh=data?Date.now()-Date.parse(data.generatedAt)<15*60_000:false;
 return <AppShell><div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-4"><SectionTitle title="Knowledge" subtitle="Curated Obsidian knowledge projected through a private, sanitized, read-only boundary."/><div className="flex gap-2"><StatusBadge label={fresh?'projection fresh':'projection aging'} status={fresh?'healthy':'warning'} pulse={fresh}/><StatusBadge label={`${data?.stats.documents??0} notes`} status="info"/></div></div>
 {error?<div className="rounded-xl border border-red-400/25 bg-red-400/[0.08] p-4 text-sm text-red-200">{error}</div>:null}
 <div className="grid gap-3 md:grid-cols-3"><div className={card2+' p-4'}><div className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">Curated notes</div><div className="mt-2 text-2xl font-bold text-slate-100">{data?.stats.documents??'—'}</div><div className={muted}>Allowlisted projection only</div></div><div className={card2+' p-4'}><div className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">Knowledge areas</div><div className="mt-2 text-2xl font-bold text-slate-100">{data?.stats.areas??'—'}</div><div className={muted}>Home, projects, areas, resources</div></div><div className={card2+' p-4'}><div className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">Last projection</div><div className="mt-2 text-base font-bold text-slate-100">{data?age(data.generatedAt):'Waiting'}</div><div className={muted}>Vault remains off-panel</div></div></div>
 <div className={card+' flex flex-wrap gap-2 p-3'}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search projects, runbooks, decisions" className="min-h-10 min-w-[240px] flex-1 rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-slate-100 outline-none focus:border-cyan-300/40"/><select value={area} onChange={event=>setArea(event.target.value)} className="min-h-10 rounded-lg border border-white/10 bg-[#111827] px-3 text-xs font-bold text-slate-200"><option value="all">All areas</option>{Object.entries(AREA_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
 <div className="grid gap-4 xl:grid-cols-[360px_1fr]"><section className={card+' overflow-hidden'}><div className="border-b border-white/10 px-4 py-3 text-xs font-bold text-slate-400">{docs.length} visible notes</div><div className="max-h-[68vh] overflow-y-auto">{docs.map(doc=><button type="button" key={doc.id} onClick={()=>setSelected(doc.id)} className="block w-full border-b border-white/[0.07] px-4 py-3 text-left hover:bg-white/[0.035]" style={{background:active?.id===doc.id?'rgba(103,213,255,.09)':undefined}}><div className="flex items-start justify-between gap-2"><strong className="text-sm text-slate-100">{doc.title}</strong><span className="text-[9px] uppercase text-slate-500">{AREA_LABELS[doc.area]||doc.area}</span></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-400">{doc.excerpt}</p><div className="mt-2 flex flex-wrap gap-1">{doc.tags.slice(0,3).map(tag=><span key={tag} className="rounded-full bg-white/5 px-2 py-0.5 text-[8px] text-cyan-200">{tag}</span>)}</div></button>)}</div></section>
 <section className={card+' overflow-hidden'}>{active?<><header className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-5 py-4"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-cyan-300/60">{active.type} · {active.status}</div><div className="mt-1 text-lg font-black text-slate-100">{active.title}</div></div><StatusBadge label={active.updated||'undated'} status="neutral"/></header><div className="max-h-[68vh] overflow-y-auto p-5"><Markdown body={active.body}/></div></>:<div className="p-8 text-sm text-slate-400">Select a note.</div>}</section></div>
 <div className={card2+' p-3 text-xs text-slate-400'}>Security boundary: no Inbox, templates, dotfiles, credentials, raw vault paths, or Obsidian authentication state are included.</div></div></AppShell>;
}

