import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { assertSafeEvent, reduceEvents, retainEvents, sanitizeAgentEvent } from './collector-core.js';
const DEFAULT_OUTPUT='/root/.openclaw/workspace/mission-control/runtime/agent-telemetry.json';
export default {id:'mission-control-observability',name:'Mission Control Observability',description:'Privacy-safe operational events for Mission Control',register(api){
  const config=api.pluginConfig||{}; const outputFile=typeof config.outputFile==='string'?config.outputFile:DEFAULT_OUTPUT; const retentionHours=Number.isInteger(config.retentionHours)?config.retentionHours:24; const maxEvents=Number.isInteger(config.maxEvents)?config.maxEvents:2000;
  let events=[]; let rejectedEvents=0; let startedAt=new Date().toISOString(); let timer; let pending=Promise.resolve();
  async function persist(){const now=Date.now();events=retainEvents(events,{nowMs:now,retentionHours,maxEvents});const payload={schemaVersion:1,generatedAt:new Date(now).toISOString(),collector:{status:'healthy',startedAt,heartbeatAt:new Date(now).toISOString(),lastEventAt:events.at(-1)?.occurredAt||null,rejectedEvents},events,work:reduceEvents(events,now)};await mkdir(dirname(outputFile),{recursive:true});const temporary=`${outputFile}.tmp`;await writeFile(temporary,`${JSON.stringify(payload)}\n`,{mode:0o600});await rename(temporary,outputFile);}
  function enqueue(operation){pending=pending.then(operation,operation);return pending;}
  api.agent.events.registerAgentEventSubscription({id:'mission-control-safe-events',description:'Allowlisted lifecycle, tool-category/outcome, and approval telemetry',streams:['lifecycle','tool','approval'],handle:(raw)=>enqueue(async()=>{try{const event=sanitizeAgentEvent(raw);if(!event||events.some(existing=>existing.eventId===event.eventId))return;events.push(event);await persist();}catch{rejectedEvents+=1;await persist();}})});
  api.registerService({id:'mission-control-observability-heartbeat',start:async()=>{startedAt=new Date().toISOString();try{const existing=JSON.parse(await readFile(outputFile,'utf8'));events=Array.isArray(existing.events)?existing.events.filter(event=>{try{assertSafeEvent(event);return true;}catch{rejectedEvents+=1;return false;}}):[];}catch{events=[];}await persist();timer=setInterval(()=>void enqueue(persist),5000);timer.unref?.();},stop:async()=>{if(timer)clearInterval(timer);await enqueue(persist);}});
}};
