'use client';

import { useEffect, useState } from 'react';
import { AppShell, Metric, SectionTitle, card, muted, pill } from '../components/ops-ui';
import { AlertTriageCard, BaselineIndicator, SystemHealthCard, ThreatTimeline, LogViewer } from '../components/security-components';

export default function Home() {
  const [overview, setOverview] = useState<any>(null);
  useEffect(() => { fetch('/api/overview', { cache: 'no-store' }).then(r => r.json()).then(setOverview).catch(()=>{}); }, []);
  return <AppShell><div className="space-y-8"><section className="grid gap-4 lg:grid-cols-5"><Metric label="Open alerts" value="12" delta="+3 in 1h" /><Metric label="Blocked attacks" value="148" delta="+18% vs baseline" /><Metric label="Top IP" value="185.193.*.*" delta="recurrent ssh" /><Metric label="Agents live" value="4" delta="all responsive" /><Metric label="Anomalous systems" value="2" delta="prod auth spike" /></section><section className="grid gap-4 xl:grid-cols-2"><div className={card + ' p-5'}><SectionTitle title="Threat summary" subtitle="What changed and why it matters" /><div className="space-y-3"><div className="text-[15px] font-semibold">Critical SSH bursts from mixed geos</div><div className={muted}>Top IPs cluster around repeated auth failures and path probing.</div><BaselineIndicator state="alert" reason="+38% auth failures vs baseline" /></div></div><div className={card + ' p-5'}><SectionTitle title="Health summary" subtitle="Baseline vs anomaly" /><div className="grid gap-3 md:grid-cols-2"><SystemHealthCard host="bazza" state="healthy" summary="Stable, within expected range" anomalies={["CPU 4% above baseline", "No auth spikes"]} /><SystemHealthCard host="prod" state="degraded" summary="Auth and disk IO elevated" anomalies={["+38% failures vs baseline", "Disk IO 2.1× baseline"]} /></div></div></section><section className="grid gap-4 xl:grid-cols-2"><ThreatTimeline /><div className={card + ' p-5'}><SectionTitle title="Latest incidents" /><div className="space-y-3"><AlertTriageCard title="Repeated SSH authentication failures" host="prod" severity="critical" evidence={["44 failed attempts in 8m", "source 185.193.*.*", "touching /root and /etc/ssh"]} /><AlertTriageCard title="Suspicious nginx path probing" host="bazza" severity="warning" evidence={["/wp-login.php", "/.git", "suspicious user agents"]} /></div></div></section><section className={card + ' p-5'}><SectionTitle title="Recent signal feed" subtitle="Structured evidence instead of raw noise" /><LogViewer rows={[{ts:'20:01:02',host:'prod',source:'ssh',actor:'185.193.*.*',action:'failed login',outcome:'critical',detail:'root password rejected'},{ts:'20:01:18',host:'bazza',source:'nginx',actor:'94.102.*.*',action:'path probe',outcome:'warning',detail:'GET /.git/config'},{ts:'20:01:41',host:'prod',source:'audit',actor:'agent',action:'baseline drift',outcome:'info',detail:'CPU and disk IO above band'}]} />{overview ? <div className="mt-4 text-[12px] text-slate-500">API online · {overview.ts}</div> : null}</section></div></AppShell>;
}
