'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { AppShell, StatusBadge } from '../../components/ops-ui';
import styles from './usage.module.css';

type Bucket={id:string;input:number;output:number;cacheRead:number;cacheWrite:number;total:number;estimatedCost:number;unpricedTokens:number};
type Billing={generatedAt:string;timezone:string;actualCost:number;coverageStart:string|null;days:{id:string;actualCost:number}[];lineItems:{id:string;actualCost:number}[]};
type Payload={ok:boolean;generatedAt:string;timezone:string;range:string;source:{transcriptCount:number;recordCount:number;lastActivity:string|null};totals:Bucket;agents:Bucket[];models:(Bucket&{provider:string})[];days:Bucket[];billing?:Billing;pricing:{sourceUrl:string;checkedAt:string;note:string}};
type Range='7d'|'30d'|'90d'|'all';
const colors={input:'#22d3ee',output:'#a78bfa',cacheRead:'#34d399',cacheWrite:'#f59e0b'};
const compact=(n:number)=>new Intl.NumberFormat('en-AU',{notation:'compact',maximumFractionDigits:2}).format(n);
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const rel=(value:string|null)=>{if(!value)return'No activity';const s=Math.max(0,(Date.now()-Date.parse(value))/1000);return s<60?'just now':s<3600?`${Math.floor(s/60)}m ago`:s<86400?`${Math.floor(s/3600)}h ago`:`${Math.floor(s/86400)}d ago`};

function StackedBars({items}:{items:Bucket[]}){const visible=items.slice(0,10),max=Math.max(1,...visible.map(x=>x.total));return <div className={styles.bars}>{visible.map(item=><div className={styles.barRow} key={item.id}><div className={styles.barLabel}><strong>{item.id}</strong><span>{compact(item.total)}</span></div><div className={styles.barTrack} title={`${item.id}: ${item.total.toLocaleString()} tokens`}>{(['input','output','cacheRead','cacheWrite'] as const).map(key=><i key={key} style={{width:`${item[key]/max*100}%`,background:colors[key]}}/>)}</div></div>)}</div>}
function Trend({days}:{days:Bucket[]}){const width=900,height=230,pad=28,max=Math.max(1,...days.map(d=>d.total));const points=days.map((d,i)=>`${pad+(i/Math.max(1,days.length-1))*(width-pad*2)},${height-pad-(d.total/max)*(height-pad*2)}`).join(' ');const area=`${pad},${height-pad} ${points} ${width-pad},${height-pad}`;return <div className={styles.chartWrap}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Token usage trend"><defs><linearGradient id="usageFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#22d3ee" stopOpacity=".34"/><stop offset="1" stopColor="#22d3ee" stopOpacity="0"/></linearGradient></defs>{[0,.25,.5,.75,1].map(v=><line key={v} x1={pad} x2={width-pad} y1={pad+v*(height-pad*2)} y2={pad+v*(height-pad*2)} stroke="rgba(148,163,184,.13)"/>)}<polygon points={area} fill="url(#usageFill)"/><polyline points={points} fill="none" stroke="#22d3ee" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>{days.map((d,i)=><circle key={d.id} cx={pad+(i/Math.max(1,days.length-1))*(width-pad*2)} cy={height-pad-(d.total/max)*(height-pad*2)} r="3" fill="#08131f" stroke="#67e8f9"><title>{d.id}: {d.total.toLocaleString()} tokens · {money(d.estimatedCost)}</title></circle>)}</svg><div className={styles.axis}><span>{days[0]?.id??'No data'}</span><span>Peak {compact(max)}</span><span>{days.at(-1)?.id??''}</span></div></div>}
function BillingTrend({days}:{days:Billing['days']}){const width=900,height=230,pad=28,max=Math.max(.01,...days.map(d=>d.actualCost));const points=days.map((d,i)=>`${pad+(i/Math.max(1,days.length-1))*(width-pad*2)},${height-pad-(d.actualCost/max)*(height-pad*2)}`).join(' ');return <div className={styles.chartWrap}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Actual OpenAI billed cost trend">{[0,.25,.5,.75,1].map(v=><line key={v} x1={pad} x2={width-pad} y1={pad+v*(height-pad*2)} y2={pad+v*(height-pad*2)} stroke="rgba(148,163,184,.13)"/>)}<polyline points={points} fill="none" stroke="#86efac" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>{days.map((d,i)=><circle key={d.id} cx={pad+(i/Math.max(1,days.length-1))*(width-pad*2)} cy={height-pad-(d.actualCost/max)*(height-pad*2)} r="3" fill="#08131f" stroke="#86efac"><title>{d.id}: {money(d.actualCost)} billed</title></circle>)}</svg><div className={styles.axis}><span>{days[0]?.id??'No billing data'}</span><span>Peak {money(max)}</span><span>{days.at(-1)?.id??''}</span></div></div>}
function Mix({data}:{data:Bucket}){const parts=(['input','output','cacheRead','cacheWrite'] as const).filter(k=>data[k]>0);return <><div className={styles.mix}>{parts.map(key=><i key={key} style={{width:`${data[key]/Math.max(1,data.total)*100}%`,background:colors[key]}} title={`${key}: ${data[key].toLocaleString()}`}/>)}</div><div className={styles.legend}>{parts.map(key=><span key={key}><i style={{background:colors[key]}}/>{key.replace(/([A-Z])/g,' $1')} <b>{(data[key]/Math.max(1,data.total)*100).toFixed(1)}%</b></span>)}</div></>}

export default function UsagePage(){
  const[range,setRange]=useState<Range>('30d'),[data,setData]=useState<Payload|null>(null),[error,setError]=useState<string|null>(null),[connected,setConnected]=useState(false),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{try{const response=await fetch(`/api/usage?range=${range}`,{cache:'no-store'});if(!response.ok)throw new Error(await response.text());setData(await response.json());setError(null)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}},[range]);
  useEffect(()=>{setLoading(true);load();const source=new EventSource(`/api/usage/stream?range=${range}`);source.addEventListener('usage',event=>{setData(JSON.parse((event as MessageEvent).data));setConnected(true);setError(null);setLoading(false)});source.onerror=()=>setConnected(false);const fallback=setInterval(load,30000);return()=>{source.close();clearInterval(fallback)}},[load,range]);
  const gap=(data?.billing?.actualCost??0)-(data?.totals.estimatedCost??0);
  return <AppShell><main className={styles.page}><header className={styles.header}><div><p>AI OPERATIONS</p><h1>Token Usage & Billing</h1><span>Recorded OpenClaw inference reconciled against actual OpenAI organization charges.</span></div><div className={styles.live}><StatusBadge label={connected?'Live · 15s':'Polling · 30s'} status={connected?'healthy':'warning'} pulse={connected}/><small>{data?`Updated ${rel(data.generatedAt)}`:'Connecting…'}</small></div></header><div className={styles.range} role="group" aria-label="Date range">{(['7d','30d','90d','all'] as Range[]).map(value=><button key={value} aria-pressed={range===value} onClick={()=>setRange(value)}>{value==='all'?'Recorded history':value.toUpperCase()}</button>)}</div>{error?<div className={styles.error}>Usage collector: {error}</div>:null}
  <section className={styles.stats}><article><span>Total tokens</span><strong>{loading?'—':compact(data?.totals.total??0)}</strong><small>Recorded OpenClaw logs</small></article><article><span>Actual billed</span><strong>{loading?'—':data?.billing?money(data.billing.actualCost):'Unavailable'}</strong><small>OpenAI Organization Costs API</small></article><article><span>OpenClaw estimate</span><strong>{loading?'—':money(data?.totals.estimatedCost??0)}</strong><small>Logged inference only</small></article><article><span>Reconciliation gap</span><strong>{loading?'—':money(gap)}</strong><small>Actual minus local estimate</small></article><article><span>Sessions indexed</span><strong>{loading?'—':(data?.source.transcriptCount??0).toLocaleString()}</strong><small>{(data?.source.recordCount??0).toLocaleString()} usage records</small></article></section>
  <section className={styles.grid}><article className={styles.wide}><div className={styles.title}><div><p>OPENAI ORGANIZATION · UTC</p><h2>Actual billed cost</h2></div><span>{data?.billing?`Coverage from ${data.billing.coverageStart}`:'Admin billing unavailable'}</span></div>{data?.billing?.days.length?<BillingTrend days={data.billing.days}/>:<div className={styles.empty}>No billing data in this period.</div>}</article><article className={styles.wide}><div className={styles.title}><div><p>OPENCLAW LOGS · PERTH</p><h2>Recorded token trend</h2></div><span>{range==='all'?'Recorded history':`Last ${range}`}</span></div>{data?.days.length?<Trend days={data.days}/>:<div className={styles.empty}>No usage in this period.</div>}</article><article><div className={styles.title}><div><p>CONSUMPTION MIX</p><h2>Token categories</h2></div></div>{data?<Mix data={data.totals}/>:null}<div className={styles.costNote}>Local estimates cover OpenClaw transcript inference only. Actual billing can include other apps, tools, images, storage, and processing tiers.</div></article><article><div className={styles.title}><div><p>BILLING LEDGER</p><h2>Top charged items</h2></div></div><div className={styles.models}>{data?.billing?.lineItems.slice(0,10).map(item=><div key={item.id}><span><strong>{item.id}</strong></span><b>{money(item.actualCost)}</b></div>)}</div></article><article><div className={styles.title}><div><p>AGENT MESH</p><h2>Usage by agent</h2></div></div>{data?<StackedBars items={data.agents}/>:null}</article><article><div className={styles.title}><div><p>MODEL LEDGER</p><h2>Recorded models</h2></div></div><div className={styles.models}>{data?.models.map(model=><div key={model.id}><span><strong>{model.id.split('/').at(-1)}</strong><small>{model.provider} · {compact(model.total)} tokens</small></span><b>{money(model.estimatedCost)}</b></div>)}</div></article></section><footer>“Actual billed” comes from OpenAI’s organization Costs API. “OpenClaw estimate” is based on locally recorded agent inference and is not an account invoice.</footer></main></AppShell>
}
